baseURL = "https://tdsg.vn/"
languageCode = "en-us"
title = "THẢM ĐẸP SÀI GÒN"
theme = "shopping-product-catalogue-simple"

Paginate = 100 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-122492141-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[blackfriday]
  angledQuotes = true
  extensions = ["hardLineBreak"]
  fractions = false
  plainIDAnchors = true

[imaging]
quality = 100


[permalinks]
  products = "/products/:title/"
  blog = "/blog/:year/:monthname/:title/"

