version: "3.5"

services:
  web:
    image: nizsheanez/tdsg
    build: ./infra/hugo
    ports:
      - "80:80"
    volumes:
      - ./:/src
    environment:
      - HUGO_ENV=production 
    command: hugo serve --bind='0.0.0.0' --port=80 --appendPort=false --baseURL='http://localhost/' --ignoreCache --cacheDir=/tmp/hugo_cache/ --renderToDisk=true
    restart: always

  admin:  
    image: nizsheanez/tdsg-admin
    build: ./infra/filebrowser
    ports:
      - "81:80"
    volumes:
      - ./:/srv
      - ./infra/filebrowser:/etc
    restart: always