version: "3.5"

services:
  web:
    image: nizsheanez/tdsg
    build: ./
    ports:
      - "1313:1313"
    volumes:
      - ./:/src
    environment:
      - HUGO_ENV=production 
    command: hugo serve --bind='0.0.0.0'
    restart: always

  admin:  
    image: nizsheanez/tdsg-admin
    build: ./admin
    ports:
      - "83:83"
    volumes:
      - ./:/srv
      - ./admin/filebrowser:/etc
    restart: always