version: "3.5"

services:
  web:
    image: nizsheanez/tdsg
    build: ./infra/hugo
    ports:
      - "80:1313"
    volumes:
      - ./:/src
    environment:
      - HUGO_ENV=production 
    command: hugo serve --bind='0.0.0.0'
    restart: always

  admin:  
    image: nizsheanez/tdsg-admin
    build: ./infra/filebrowser
    ports:
      - "81:81"
    volumes:
      - ./:/srv
      - ./admin/filebrowser:/etc
    restart: always