version: "3.5"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  web:
    image: nizsheanez/tdsg
    build: ./infra/hugo
    volumes:
      - ./:/src
    environment:
      HUGO_ENV: production 
      VIRTUAL_HOST: ${HOST}
    expose:
      - 80
    command: hugo serve --bind='0.0.0.0' --port=80 --appendPort=false --baseURL='http://${HOST}/' --disableLiveReload=true
    restart: always

  admin:  
    image: nizsheanez/tdsg-admin
    build: ./infra/filebrowser
    environment:
      VIRTUAL_HOST: admin.${HOST}
    expose:
      - 80
    volumes:
      - ./:/srv
      - ./infra/filebrowser:/etc
    restart: always

